import { MovementPattern, Equipment, Exercise, Zone, GoalTarget, MuscleGroup } from './types';

export const INITIAL_GOAL_TARGETS: GoalTarget[] = [
  { id: 'target-push', name: 'PUSH-MUSKLER', targetSets: 50, muscleGroups: ['Bröst', 'Axlar', 'Triceps'] },
  { id: 'target-pull', name: 'PULL-MUSKLER', targetSets: 27, muscleGroups: ['Rygg', 'Biceps', 'Underarmar', 'Trapezius'] },
  { id: 'target-legs', name: 'BEN-MUSKLER', targetSets: 45, muscleGroups: ['Framsida lår', 'Baksida lår', 'Säte', 'Vader'] }
];

export const EXERCISE_DATABASE: Exercise[] = [
  // ==========================================
  // HYROX & FUNCTIONAL FITNESS
  // ==========================================
  {
    id: 'hyrox-1',
    name: 'SkiErg',
    englishName: 'Ski Ergometer',
    pattern: MovementPattern.VERTICAL_PULL,
    tier: 'tier_1',
    primaryMuscles: ['Rygg', 'Triceps'],
    secondaryMuscles: ['Mage', 'Baksida lår', 'Säte', 'Axlar'],
    muscleGroups: ['Rygg', 'Triceps', 'Mage', 'Baksida lår', 'Säte', 'Axlar'],
    equipment: [Equipment.SKI_ERG],
    difficultyMultiplier: 1.3,
    bodyweightCoefficient: 0,
    trackingType: 'time_distance',
    description: 'Hyrox Station 1. Fokusera på explosiv höftfällning och bålspänning för maximal kraft.',
    alternativeExIds: ['g-ry-22', 'g-ry-3']
  },
  {
    id: 'hyrox-2',
    name: 'Sled Push',
    englishName: 'Sled Push',
    pattern: MovementPattern.SQUAT,
    tier: 'tier_1',
    primaryMuscles: ['Framsida lår', 'Säte'],
    secondaryMuscles: ['Vader', 'Axlar', 'Mage'],
    muscleGroups: ['Framsida lår', 'Säte', 'Vader', 'Axlar', 'Mage'],
    equipment: [Equipment.SLED],
    difficultyMultiplier: 1.5,
    bodyweightCoefficient: 0,
    trackingType: 'time_distance',
    description: 'Hyrox Station 2. Håll en låg, framåtlutad position och tryck med korta, kraftfulla steg.',
    alternativeExIds: ['g-be-2', 'g-be-1']
  },
  {
    id: 'hyrox-3',
    name: 'Sled Pull',
    englishName: 'Sled Pull',
    pattern: MovementPattern.HORIZONTAL_PULL,
    tier: 'tier_1',
    primaryMuscles: ['Rygg', 'Biceps'],
    secondaryMuscles: ['Underarmar', 'Ryggslut', 'Säte'],
    muscleGroups: ['Rygg', 'Biceps', 'Underarmar', 'Ryggslut', 'Säte'],
    equipment: [Equipment.SLED],
    difficultyMultiplier: 1.4,
    bodyweightCoefficient: 0,
    trackingType: 'time_distance',
    description: 'Hyrox Station 3. Dra släden mot dig med hand-över-hand-teknik. Håll låg tyngdpunkt.',
    alternativeExIds: ['g-ry-4', 'g-ry-23']
  },
  {
    id: 'hyrox-4',
    name: 'Burpee Broad Jump',
    englishName: 'Burpee Broad Jump',
    pattern: MovementPattern.EXPLOSIVE,
    tier: 'tier_1',
    primaryMuscles: ['Bröst', 'Framsida lår', 'Säte'],
    secondaryMuscles: ['Axlar', 'Triceps', 'Mage'],
    muscleGroups: ['Bröst', 'Framsida lår', 'Säte', 'Axlar', 'Triceps', 'Mage'],
    equipment: [Equipment.BODYWEIGHT],
    difficultyMultiplier: 1.6,
    bodyweightCoefficient: 1.0,
    trackingType: 'reps_only',
    description: 'Hyrox Station 4. Bröst mot golv, hoppa framåt med kraft och landa stabilt.',
    alternativeExIds: ['h-br-1', 'h-be-10']
  },
  {
    id: 'hyrox-5',
    name: 'RowErg',
    englishName: 'Rowing Ergometer',
    pattern: MovementPattern.HORIZONTAL_PULL,
    tier: 'tier_1',
    primaryMuscles: ['Rygg', 'Framsida lår'],
    secondaryMuscles: ['Biceps', 'Baksida lår', 'Säte'],
    muscleGroups: ['Rygg', 'Framsida lår', 'Biceps', 'Baksida lår', 'Säte'],
    equipment: [Equipment.ROWER],
    difficultyMultiplier: 1.3,
    bodyweightCoefficient: 0,
    trackingType: 'time_distance',
    description: 'Hyrox Station 5. Kraftfull benspark följt av ett drag med rygg och armar. Ben-Rygg-Armar, Armar-Rygg-Ben.',
    alternativeExIds: ['g-ry-4']
  },
  {
    id: 'hyrox-6',
    name: 'Farmers Carry',
    englishName: 'Farmers Carry',
    pattern: MovementPattern.CORE,
    tier: 'tier_2',
    primaryMuscles: ['Underarmar', 'Trapezius'],
    secondaryMuscles: ['Mage', 'Ryggslut'],
    muscleGroups: ['Underarmar', 'Trapezius', 'Mage', 'Ryggslut'],
    equipment: [Equipment.KETTLEBELL],
    difficultyMultiplier: 1.2,
    bodyweightCoefficient: 0,
    trackingType: 'time_distance',
    description: 'Hyrox Station 6. Gå med tunga vikter i händerna. Håll stolt hållning och spänn bålen.',
    alternativeExIds: ['g-co-1', 'g-ry-19']
  },
  {
    id: 'hyrox-7',
    name: 'Sandbag Lunges',
    englishName: 'Sandbag Lunges',
    pattern: MovementPattern.LUNGE,
    tier: 'tier_1',
    primaryMuscles: ['Framsida lår', 'Säte'],
    secondaryMuscles: ['Baksida lår', 'Mage'],
    muscleGroups: ['Framsida lår', 'Säte', 'Baksida lår', 'Mage'],
    equipment: [Equipment.SANDBAG],
    difficultyMultiplier: 1.4,
    bodyweightCoefficient: 0,
    trackingType: 'reps_only',
    description: 'Hyrox Station 7. Utfall med sandsäck på axlarna. Knät ska nudda marken i varje repetition.',
    alternativeExIds: ['g-be-11', 'g-be-12']
  },
  {
    id: 'hyrox-8',
    name: 'Wall Balls',
    englishName: 'Wall Balls',
    pattern: MovementPattern.SQUAT,
    tier: 'tier_1',
    primaryMuscles: ['Framsida lår', 'Axlar', 'Säte'],
    secondaryMuscles: ['Triceps', 'Mage'],
    muscleGroups: ['Framsida lår', 'Axlar', 'Säte', 'Triceps', 'Mage'],
    equipment: [Equipment.MEDICINE_BALL],
    difficultyMultiplier: 1.5,
    bodyweightCoefficient: 0,
    trackingType: 'reps_only',
    description: 'Hyrox Station 8. Knäböj under 90 grader och kasta bollen explosivt mot målet.',
    alternativeExIds: ['g-be-4', 'g-ax-15']
  },
  {
    id: 'func-1',
    name: 'Assault Bike',
    englishName: 'Air Bike Sprints',
    pattern: MovementPattern.CARDIO,
    tier: 'tier_2',
    primaryMuscles: ['Framsida lår', 'Säte', 'Bröst', 'Rygg'],
    secondaryMuscles: [],
    muscleGroups: ['Framsida lår', 'Säte', 'Bröst', 'Rygg'],
    equipment: [Equipment.ASSAULT_BIKE],
    difficultyMultiplier: 1.6,
    bodyweightCoefficient: 0,
    trackingType: 'time_distance',
    description: 'Maximal ansträngning på Assault Bike. Använd både armar och ben för att generera kraft.',
    alternativeExIds: ['hyrox-1', 'hyrox-5']
  },
  {
    id: 'func-2',
    name: 'Löpning (Lutning)',
    englishName: 'Incline Running',
    pattern: MovementPattern.CARDIO,
    tier: 'tier_2',
    primaryMuscles: ['Framsida lår', 'Säte', 'Vader'],
    secondaryMuscles: ['Baksida lår'],
    muscleGroups: ['Framsida lår', 'Säte', 'Vader', 'Baksida lår'],
    equipment: [Equipment.TREADMILL],
    difficultyMultiplier: 1.2,
    bodyweightCoefficient: 1.0,
    trackingType: 'time_distance',
    description: 'Löpning på löpband med hög lutning för att simulera backträning och bygga styrka.',
    alternativeExIds: ['g-be-11']
  },
  {
    id: 'func-3',
    name: 'Box Jumps',
    englishName: 'Box Jumps',
    pattern: MovementPattern.EXPLOSIVE,
    tier: 'tier_2',
    primaryMuscles: ['Säte', 'Framsida lår'],
    secondaryMuscles: ['Vader', 'Baksida lår'],
    muscleGroups: ['Säte', 'Framsida lår', 'Vader', 'Baksida lår'],
    equipment: [Equipment.BOX],
    difficultyMultiplier: 1.3,
    bodyweightCoefficient: 1.0,
    trackingType: 'reps_only',
    description: 'Explosivt hopp upp på en låda. Landa mjukt och kliv ner kontrollerat.',
    alternativeExIds: ['g-be-1']
  },
  {
    id: 'func-4',
    name: 'Devil Press',
    englishName: 'Devil Press',
    pattern: MovementPattern.EXPLOSIVE,
    tier: 'tier_1',
    primaryMuscles: ['Bröst', 'Säte', 'Axlar'],
    secondaryMuscles: ['Triceps', 'Ryggslut'],
    muscleGroups: ['Bröst', 'Säte', 'Axlar', 'Triceps', 'Ryggslut'],
    equipment: [Equipment.DUMBBELL],
    difficultyMultiplier: 1.7,
    bodyweightCoefficient: 0.8,
    trackingType: 'reps_only',
    description: 'En burpee följt av att svinga hantlarna från golvet till över huvudet i en rörelse.',
    alternativeExIds: ['hyrox-4', 'oly-2']
  },
  {
    id: 'func-5',
    name: 'Thrusters (Skivstång)',
    englishName: 'Barbell Thrusters',
    pattern: MovementPattern.SQUAT,
    tier: 'tier_1',
    primaryMuscles: ['Framsida lår', 'Axlar'],
    secondaryMuscles: ['Säte', 'Triceps', 'Mage'],
    muscleGroups: ['Framsida lår', 'Axlar', 'Säte', 'Triceps', 'Mage'],
    equipment: [Equipment.BARBELL],
    difficultyMultiplier: 1.4,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'En frontböj direkt över i en militärpress. Håll bålen spänd genom hela lyftet.',
    alternativeExIds: ['hyrox-8', 'g-be-3']
  },

  // ==========================================
  // BEN - PRESS & BÖJ
  // ==========================================
  {
    id: 'g-be-1',
    name: 'Knäböj (High Bar)',
    englishName: 'Barbell Back Squat (High Bar)',
    pattern: MovementPattern.SQUAT,
    tier: 'tier_1',
    primaryMuscles: ['Framsida lår', 'Säte'],
    secondaryMuscles: ['Ryggslut', 'Mage', 'Adduktorer'],
    muscleGroups: ['Framsida lår', 'Säte', 'Ryggslut', 'Mage', 'Adduktorer'],
    equipment: [Equipment.BARBELL],
    difficultyMultiplier: 1.2,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Klassisk knäböj med stången högt på axlarna för quadsfokus.',
    alternativeExIds: ['g-be-2', 'g-be-3', 'g-be-5']
  },
  {
    id: 'g-be-2',
    name: 'Benpress',
    englishName: 'Leg Press',
    pattern: MovementPattern.SQUAT,
    tier: 'tier_2',
    primaryMuscles: ['Framsida lår'],
    secondaryMuscles: ['Säte', 'Adduktorer'],
    muscleGroups: ['Framsida lår', 'Säte', 'Adduktorer'],
    equipment: [Equipment.LEG_PRESS],
    difficultyMultiplier: 1.0,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Maskinövning som isolerar benen. Bra för att bygga volym utan att belasta ryggen.',
    alternativeExIds: ['g-be-1', 'g-be-5']
  },
  {
    id: 'g-be-3',
    name: 'Frontböj',
    englishName: 'Front Squat',
    pattern: MovementPattern.SQUAT,
    tier: 'tier_1',
    primaryMuscles: ['Framsida lår', 'Mage'],
    secondaryMuscles: ['Säte', 'Rygg'],
    muscleGroups: ['Framsida lår', 'Mage', 'Säte', 'Rygg'],
    equipment: [Equipment.BARBELL],
    difficultyMultiplier: 1.3,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Knäböj med stången på framsidan av axlarna. Kräver och bygger en stark bål.',
    alternativeExIds: ['g-be-1', 'g-be-4']
  },
  {
    id: 'g-be-5',
    name: 'Hack Squat',
    englishName: 'Hack Squat Machine',
    pattern: MovementPattern.SQUAT,
    tier: 'tier_2',
    primaryMuscles: ['Framsida lår'],
    secondaryMuscles: ['Säte'],
    muscleGroups: ['Framsida lår', 'Säte'],
    equipment: [Equipment.HACK_SQUAT],
    difficultyMultiplier: 1.1,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Maskin som efterliknar knäböj men med mer stöd för ryggen. Utmärkt för quad-isolering.',
    alternativeExIds: ['g-be-2', 'g-be-1', 'g-be-22']
  },
  {
    id: 'g-be-11',
    name: 'Gående Utfall (Hantlar)',
    englishName: 'Walking Lunges (Dumbbells)',
    pattern: MovementPattern.LUNGE,
    tier: 'tier_2',
    primaryMuscles: ['Framsida lår', 'Säte'],
    secondaryMuscles: ['Vader', 'Mage', 'Baksida lår'],
    muscleGroups: ['Framsida lår', 'Säte', 'Vader', 'Baksida lår', 'Mage'],
    equipment: [Equipment.DUMBBELL],
    difficultyMultiplier: 1.1,
    bodyweightCoefficient: 0.5,
    trackingType: 'reps_weight',
    description: 'Gående utfall med vikter. En fantastisk funktionell övning för benstyrka och balans.',
    alternativeExIds: ['hyrox-7', 'g-be-12']
  },
  {
    id: 'g-be-12',
    name: 'Bulgariska Utfall',
    englishName: 'Bulgarian Split Squat',
    pattern: MovementPattern.LUNGE,
    tier: 'tier_2',
    primaryMuscles: ['Säte', 'Framsida lår'],
    secondaryMuscles: ['Baksida lår', 'Mage'],
    muscleGroups: ['Säte', 'Framsida lår', 'Baksida lår', 'Mage'],
    equipment: [Equipment.DUMBBELL, Equipment.BENCH],
    difficultyMultiplier: 1.2,
    bodyweightCoefficient: 0.8,
    trackingType: 'reps_weight',
    description: 'Enbensknäböj med bakre foten eleverad. Brutalt effektiv för sätes- och benutveckling.',
    alternativeExIds: ['g-be-11', 'g-be-23']
  },
  {
    id: 'g-be-20',
    name: 'Benspark',
    englishName: 'Leg Extension',
    pattern: MovementPattern.ISOLATION,
    tier: 'tier_3',
    primaryMuscles: ['Framsida lår'],
    secondaryMuscles: [],
    muscleGroups: ['Framsida lår'],
    equipment: [Equipment.LEG_EXTENSION],
    difficultyMultiplier: 0.7,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Isoleringsövning för framsida lår (quadriceps). Bra för att bygga volym och som avslutare.',
    alternativeExIds: []
  },
  
  // ==========================================
  // BEN - DRAG & HÖFT
  // ==========================================
  {
    id: 'g-ry-1',
    name: 'Marklyft',
    englishName: 'Conventional Deadlift',
    pattern: MovementPattern.HINGE,
    tier: 'tier_1',
    primaryMuscles: ['Ryggslut', 'Säte', 'Baksida lår'],
    secondaryMuscles: ['Trapezius', 'Underarmar', 'Rygg'],
    muscleGroups: ['Ryggslut', 'Säte', 'Baksida lår', 'Trapezius', 'Underarmar', 'Rygg'],
    equipment: [Equipment.BARBELL],
    difficultyMultiplier: 1.25,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Kungen av styrkeövningar. Lyft stången från marken med rak rygg.',
    alternativeExIds: ['g-ry-2', 'g-ry-19']
  },
  {
    id: 'g-be-6',
    name: 'Rumänska Marklyft',
    englishName: 'Romanian Deadlift (RDL)',
    pattern: MovementPattern.HINGE,
    tier: 'tier_2',
    primaryMuscles: ['Baksida lår', 'Säte'],
    secondaryMuscles: ['Ryggslut', 'Underarmar'],
    muscleGroups: ['Baksida lår', 'Säte', 'Ryggslut', 'Underarmar'],
    equipment: [Equipment.BARBELL],
    difficultyMultiplier: 1.0,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Fokus på att fälla i höften med nästan raka ben för att stretcha och stärka baksida lår.',
    alternativeExIds: ['g-be-7', 'g-ry-1']
  },
  {
    id: 'g-be-8',
    name: 'Hip Thrust',
    englishName: 'Barbell Hip Thrust',
    pattern: MovementPattern.HINGE,
    tier: 'tier_1',
    primaryMuscles: ['Säte'],
    secondaryMuscles: ['Baksida lår', 'Ryggslut'],
    muscleGroups: ['Säte', 'Baksida lår', 'Ryggslut'],
    equipment: [Equipment.BARBELL, Equipment.BENCH],
    difficultyMultiplier: 0.9,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Den bästa övningen för att bygga en stark och explosiv sätesmuskulatur.',
    alternativeExIds: ['g-be-9']
  },
  {
    id: 'g-be-10',
    name: 'Lårcurl (Liggande)',
    englishName: 'Lying Leg Curl',
    pattern: MovementPattern.ISOLATION,
    tier: 'tier_3',
    primaryMuscles: ['Baksida lår'],
    secondaryMuscles: ['Vader'],
    muscleGroups: ['Baksida lår', 'Vader'],
    equipment: [Equipment.LEG_CURL],
    difficultyMultiplier: 0.7,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Isoleringsövning för hamstrings. Fokusera på att "klämma" ihop muskeln i toppen.',
    alternativeExIds: ['g-be-10s']
  },
  {
    id: 'func-6',
    name: 'Kettlebell Swing',
    englishName: 'Kettlebell Swing',
    pattern: MovementPattern.HINGE,
    tier: 'tier_2',
    primaryMuscles: ['Säte', 'Baksida lår'],
    secondaryMuscles: ['Ryggslut', 'Mage'],
    muscleGroups: ['Säte', 'Baksida lår', 'Ryggslut', 'Mage'],
    equipment: [Equipment.KETTLEBELL],
    difficultyMultiplier: 1.3,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Explosiv höftfällning som bygger arbetskapacitet och styrka i hela bakre kedjan.',
    alternativeExIds: ['g-ry-1', 'g-be-6']
  },
  
  // ==========================================
  // RYGG & DRAG
  // ==========================================
  {
    id: 'g-ry-2',
    name: 'Pull-ups',
    englishName: 'Pull-ups',
    pattern: MovementPattern.VERTICAL_PULL,
    tier: 'tier_1',
    primaryMuscles: ['Rygg'],
    secondaryMuscles: ['Biceps', 'Underarmar'],
    muscleGroups: ['Rygg', 'Biceps', 'Underarmar'],
    equipment: [Equipment.PULLUP_BAR],
    difficultyMultiplier: 1.4,
    bodyweightCoefficient: 1.0,
    trackingType: 'reps_only',
    description: 'Räckhäv med pronerat (handflator bort) grepp. En grundsten för ryggstyrka.',
    alternativeExIds: ['g-ry-3', 'g-ry-2w']
  },
  {
    id: 'g-ry-3',
    name: 'Latsdrag',
    englishName: 'Lat Pulldown',
    pattern: MovementPattern.VERTICAL_PULL,
    tier: 'tier_2',
    primaryMuscles: ['Rygg'],
    secondaryMuscles: ['Biceps', 'Axlar'],
    muscleGroups: ['Rygg', 'Biceps', 'Axlar'],
    equipment: [Equipment.LAT_PULLDOWN],
    difficultyMultiplier: 0.85,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Simulerar en pull-up i maskin. Utmärkt för att bygga volym och styrka i latsen.',
    alternativeExIds: ['g-ry-2', 'g-ry-22', 'h-ry-2']
  },
  {
    id: 'g-ry-4',
    name: 'Stångrodd',
    englishName: 'Barbell Bent Over Row',
    pattern: MovementPattern.HORIZONTAL_PULL,
    tier: 'tier_1',
    primaryMuscles: ['Rygg'],
    secondaryMuscles: ['Biceps', 'Ryggslut', 'Trapezius'],
    muscleGroups: ['Rygg', 'Biceps', 'Ryggslut', 'Trapezius'],
    equipment: [Equipment.BARBELL],
    difficultyMultiplier: 1.1,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'En av de bästa övningarna för att bygga en tjock och stark rygg. Håll ryggen rak!',
    alternativeExIds: ['g-ry-5', 'g-ry-6']
  },
  {
    id: 'g-ry-5',
    name: 'Hantelrodd',
    englishName: 'Dumbbell Row',
    pattern: MovementPattern.HORIZONTAL_PULL,
    tier: 'tier_2',
    primaryMuscles: ['Rygg'],
    secondaryMuscles: ['Biceps', 'Underarmar'],
    muscleGroups: ['Rygg', 'Biceps', 'Underarmar'],
    equipment: [Equipment.DUMBBELL, Equipment.BENCH],
    difficultyMultiplier: 0.9,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Enarmsrodd som tillåter ett stort rörelseutslag och bygger unilateral styrka.',
    alternativeExIds: ['g-ry-4', 'g-ry-6']
  },
  {
    id: 'g-ry-10',
    name: 'Face Pulls',
    englishName: 'Face Pulls',
    pattern: MovementPattern.HORIZONTAL_PULL,
    tier: 'tier_3',
    primaryMuscles: ['Axlar', 'Trapezius'],
    secondaryMuscles: ['Rotatorcuff'],
    muscleGroups: ['Axlar', 'Trapezius', 'Rotatorcuff'],
    equipment: [Equipment.CABLES],
    difficultyMultiplier: 0.6,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'En "skottsäker" övning för axelhälsa. Dra repet mot ansiktet och rotera utåt i slutet.',
    alternativeExIds: ['g-ax-10']
  },

  // ==========================================
  // BRÖST & PRESS
  // ==========================================
  {
    id: 'g-br-1',
    name: 'Bänkpress',
    englishName: 'Bench Press',
    pattern: MovementPattern.HORIZONTAL_PUSH,
    tier: 'tier_1',
    primaryMuscles: ['Bröst'],
    secondaryMuscles: ['Triceps', 'Axlar'],
    muscleGroups: ['Bröst', 'Triceps', 'Axlar'],
    equipment: [Equipment.BARBELL, Equipment.BENCH],
    difficultyMultiplier: 1.0,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Grundövning för överkroppspress. Sänk stången kontrollerat till bröstet och pressa explosivt upp.',
    alternativeExIds: ['g-br-2', 'g-br-3', 'h-br-1']
  },
  {
    id: 'g-br-2',
    name: 'Lutande Hantelpress',
    englishName: 'Incline Dumbbell Press',
    pattern: MovementPattern.HORIZONTAL_PUSH,
    tier: 'tier_2',
    primaryMuscles: ['Bröst', 'Axlar'],
    secondaryMuscles: ['Triceps'],
    muscleGroups: ['Bröst', 'Axlar', 'Triceps'],
    equipment: [Equipment.DUMBBELL, Equipment.BENCH],
    difficultyMultiplier: 0.9,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Press på lutande bänk för att fokusera på övre delen av bröstmuskeln.',
    alternativeExIds: ['g-br-1', 'g-br-3']
  },
  {
    id: 'g-ax-1',
    name: 'Militärpress (Stående)',
    englishName: 'Overhead Press (Standing)',
    pattern: MovementPattern.VERTICAL_PUSH,
    tier: 'tier_1',
    primaryMuscles: ['Axlar'],
    secondaryMuscles: ['Triceps', 'Mage', 'Trapezius'],
    muscleGroups: ['Axlar', 'Triceps', 'Mage', 'Trapezius'],
    equipment: [Equipment.BARBELL],
    difficultyMultiplier: 1.1,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Stående press med skivstång. Kräver och bygger total kroppsstabilitet.',
    alternativeExIds: ['g-ax-2', 'g-ax-16']
  },
  {
    id: 'g-ax-2',
    name: 'Sittande Axelpress (Hantlar)',
    englishName: 'Seated Dumbbell Shoulder Press',
    pattern: MovementPattern.VERTICAL_PUSH,
    tier: 'tier_2',
    primaryMuscles: ['Axlar'],
    secondaryMuscles: ['Triceps'],
    muscleGroups: ['Axlar', 'Triceps'],
    equipment: [Equipment.DUMBBELL, Equipment.BENCH],
    difficultyMultiplier: 0.9,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Sittande axelpress som isolerar axlarna mer än den stående varianten.',
    alternativeExIds: ['g-ax-1', 'g-ax-3']
  },
  {
    id: 'g-ax-4',
    name: 'Sidolyft (Hantlar)',
    englishName: 'Dumbbell Lateral Raises',
    pattern: MovementPattern.ISOLATION,
    tier: 'tier_3',
    primaryMuscles: ['Axlar'],
    secondaryMuscles: [],
    muscleGroups: ['Axlar'],
    equipment: [Equipment.DUMBBELL],
    difficultyMultiplier: 0.7,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Lyft hantlarna rakt ut åt sidan för att bygga bredd på axlarna. Lätt vikt och strikt form är nyckeln.',
    alternativeExIds: ['g-ax-21']
  },
  {
    id: 'g-ar-10',
    name: 'Dips',
    englishName: 'Dips',
    pattern: MovementPattern.HORIZONTAL_PUSH,
    tier: 'tier_2',
    primaryMuscles: ['Triceps', 'Bröst'],
    secondaryMuscles: ['Axlar'],
    muscleGroups: ['Triceps', 'Bröst', 'Axlar'],
    equipment: [Equipment.DIP_STATION],
    difficultyMultiplier: 1.3,
    bodyweightCoefficient: 1.0,
    trackingType: 'reps_only',
    description: 'En fantastisk kroppsviktsövning för bröst och triceps. Luta dig framåt för mer bröstfokus.',
    alternativeExIds: ['g-ar-15', 'g-br-1']
  },

  // ==========================================
  // ARMAR, BÅL & LÖPAR-PREHAB (Många Tier 3)
  // ==========================================
  {
    id: 'g-ar-1',
    name: 'Skivstångscurl',
    englishName: 'Barbell Bicep Curl',
    pattern: MovementPattern.ISOLATION,
    tier: 'tier_3',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Underarmar'],
    muscleGroups: ['Biceps', 'Underarmar'],
    equipment: [Equipment.BARBELL],
    difficultyMultiplier: 0.7,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Klassisk biceps-byggare. Undvik att svinga och fokusera på muskelkontakt.',
    alternativeExIds: ['g-ar-2']
  },
  {
    id: 'g-ar-3',
    name: 'Triceps Pushdown (Rep)',
    englishName: 'Triceps Rope Pushdown',
    pattern: MovementPattern.ISOLATION,
    tier: 'tier_3',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: [],
    muscleGroups: ['Triceps'],
    equipment: [Equipment.CABLES],
    difficultyMultiplier: 0.65,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Pressa ner repet i kabelmaskinen. Sära på händerna i botten för maximal kontraktion.',
    alternativeExIds: ['g-ar-15', 'h-br-2']
  },
  {
    id: 'r-lb-1',
    name: 'Tåhävningar (Stående)',
    englishName: 'Standing Calf Raises',
    pattern: MovementPattern.ISOLATION,
    tier: 'tier_3',
    primaryMuscles: ['Vader'],
    secondaryMuscles: [],
    muscleGroups: ['Vader'],
    equipment: [Equipment.CALF_RAISE, Equipment.SMITH_MACHINE, Equipment.BODYWEIGHT],
    difficultyMultiplier: 0.6,
    bodyweightCoefficient: 1.0,
    trackingType: 'reps_weight',
    description: 'Stärker vadmusklerna, viktigt för ett effektivt och skadefritt löpsteg.',
    alternativeExIds: ['r-lb-2']
  },
  {
    id: 'r-lb-4',
    name: 'Tibialis Raise',
    englishName: 'Tibialis Raise',
    pattern: MovementPattern.REHAB,
    tier: 'tier_3',
    primaryMuscles: ['Tibialis'],
    secondaryMuscles: [],
    muscleGroups: ['Tibialis'],
    equipment: [Equipment.BODYWEIGHT],
    difficultyMultiplier: 0.5,
    bodyweightCoefficient: 0.5,
    trackingType: 'reps_only',
    description: 'Stärker muskeln på framsidan av underbenet, kritiskt för att förebygga benhinneinflammation.',
    alternativeExIds: []
  },
  {
    id: 'g-co-1',
    name: 'Hängande Benlyft',
    englishName: 'Hanging Leg Raises',
    pattern: MovementPattern.CORE,
    tier: 'tier_2',
    primaryMuscles: ['Mage', 'Höftböjare'],
    secondaryMuscles: ['Underarmar'],
    muscleGroups: ['Mage', 'Höftböjare', 'Underarmar'],
    equipment: [Equipment.PULLUP_BAR],
    difficultyMultiplier: 1.2,
    bodyweightCoefficient: 0.5,
    trackingType: 'reps_only',
    description: 'En avancerad bålövning som bygger enorm styrka i de nedre magmusklerna.',
    alternativeExIds: ['g-co-2']
  },
  {
    id: 'g-co-5',
    name: 'Plankan',
    englishName: 'Plank',
    pattern: MovementPattern.CORE,
    tier: 'tier_3',
    primaryMuscles: ['Mage'],
    secondaryMuscles: ['Ryggslut', 'Axlar'],
    muscleGroups: ['Mage', 'Ryggslut', 'Axlar'],
    equipment: [Equipment.BODYWEIGHT],
    difficultyMultiplier: 0.8,
    bodyweightCoefficient: 0.7,
    trackingType: 'time_only',
    description: 'Isometrisk bålövning. Håll en rak linje från huvud till hälar och spänn magen.',
    alternativeExIds: ['g-co-6']
  },
  
  // ==========================================
  // OLYMPISKA LYFT & EXPLOSIVITET
  // ==========================================
  {
    id: 'oly-1',
    name: 'Frivändning',
    englishName: 'Power Clean',
    pattern: MovementPattern.EXPLOSIVE,
    tier: 'tier_1',
    primaryMuscles: ['Säte', 'Framsida lår', 'Trapezius'],
    secondaryMuscles: ['Ryggslut', 'Axlar'],
    muscleGroups: ['Säte', 'Framsida lår', 'Trapezius', 'Ryggslut', 'Axlar'],
    equipment: [Equipment.BARBELL],
    difficultyMultiplier: 1.8,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Explosivt lyft från golvet till axlarna. Bygger total kroppsstyrka och kraftutveckling.',
    alternativeExIds: ['oly-2']
  },
  {
    id: 'oly-2',
    name: 'Ryck',
    englishName: 'Snatch',
    pattern: MovementPattern.EXPLOSIVE,
    tier: 'tier_1',
    primaryMuscles: ['Säte', 'Framsida lår', 'Axlar'],
    secondaryMuscles: ['Trapezius', 'Ryggslut'],
    muscleGroups: ['Säte', 'Framsida lår', 'Axlar', 'Trapezius', 'Ryggslut'],
    equipment: [Equipment.BARBELL],
    difficultyMultiplier: 2.0,
    bodyweightCoefficient: 0,
    trackingType: 'reps_weight',
    description: 'Det mest tekniskt krävande lyftet. Stången går från golvet till över huvudet i en enda rörelse.',
    alternativeExIds: ['oly-1']
  }
];

export const INITIAL_ZONES: Zone[] = [
  { id: 'zone-a', name: 'Hemma', inventory: [Equipment.DUMBBELL, Equipment.BANDS, Equipment.BODYWEIGHT, Equipment.PULLUP_BAR, Equipment.BENCH], icon: 'home' },
  { id: 'zone-b', name: 'Gymmet', inventory: Object.values(Equipment), icon: 'building' },
  { id: 'zone-c', name: 'Resa', inventory: [Equipment.BODYWEIGHT, Equipment.BANDS], icon: 'briefcase' }
];